/* Generated by Qubu. Do not edit this machine-owned file. */
import * as _qubu from 'qubu'

type _CatalogColumnOptions<TOutput, TInsert> = Omit<
  _qubu.ColumnOptions<TOutput, TInsert>,
  'storage'
> & {
  readonly storage?: never
}

const _catalogColumn =
  <
    TOutput = unknown,
    TInsert = unknown,
    TUpdate = unknown,
    TSqlType extends _qubu.AnySqlType = _qubu.SqlUnknown,
  >() =>
  <
    const TDialect extends string,
    const TDeclaration extends string,
    const TOptions extends _CatalogColumnOptions<TOutput, TInsert>,
  >(
    dialect: TDialect,
    declaration: TDeclaration,
    options: TOptions
  ) =>
    _qubu.nativeColumn<
      TOutput,
      TInsert,
      TUpdate,
      TOptions,
      TSqlType,
      TDialect,
      TDeclaration
    >(_qubu.nativeStorage(dialect, declaration), options)

const _AlphaRecordsDefinitions = {
  betaId: _catalogColumn<unknown, unknown, unknown, _qubu.SqlInteger>()(
    'postgresql',
    'integer',
    {
      nullable: false,
      sqlName: 'beta_id',
    }
  ),
  id: _catalogColumn<unknown, unknown, unknown, _qubu.SqlInteger>()(
    'postgresql',
    'integer',
    {
      nullable: false,
      sqlName: 'id',
    }
  ),
}

type _AlphaRecordsColumns = _qubu.TableColumns<
  typeof _AlphaRecordsDefinitions,
  _qubu.TableIdentity<'alpha_records'>
>

type _AlphaRecordsConstraints = {
  readonly alphaRecordsBetaFk: _qubu.ForeignKeyConstraint<
    readonly [_AlphaRecordsColumns['betaId']]
  >
  readonly alphaRecordsPkey: _qubu.KeyConstraint<
    'primary-key',
    readonly [_AlphaRecordsColumns['id']]
  >
}

type _AlphaRecordsIndexes = {}

type _AlphaRecordsTable = _qubu.Table<
  'alpha_records',
  typeof _AlphaRecordsDefinitions,
  _AlphaRecordsConstraints,
  _AlphaRecordsIndexes
> & {
  readonly columns: _AlphaRecordsColumns
}

export const alphaRecords: _AlphaRecordsTable = _qubu.table(
  'alpha_records',
  _AlphaRecordsDefinitions,
  _current => ({
    constraints: {
      alphaRecordsBetaFk: _qubu.catalogForeignKey(
        [_current.columns['betaId']],
        () => _qubu.references(betaRecords, betaRecords.columns['id']),
        { physicalName: 'alpha_records_beta_fk' }
      ),
      alphaRecordsPkey: _qubu.primaryKey(_current.columns['id'], {
        physicalName: 'alpha_records_pkey',
      }),
    },
    indexes: {},
  })
)

const _BetaRecordsDefinitions = {
  alphaId: _catalogColumn<unknown, unknown, unknown, _qubu.SqlInteger>()(
    'postgresql',
    'integer',
    {
      nullable: false,
      sqlName: 'alpha_id',
    }
  ),
  id: _catalogColumn<unknown, unknown, unknown, _qubu.SqlInteger>()(
    'postgresql',
    'integer',
    {
      nullable: false,
      sqlName: 'id',
    }
  ),
}

type _BetaRecordsColumns = _qubu.TableColumns<
  typeof _BetaRecordsDefinitions,
  _qubu.TableIdentity<'beta_records'>
>

type _BetaRecordsConstraints = {
  readonly betaRecordsAlphaFk: _qubu.ForeignKeyConstraint<
    readonly [_BetaRecordsColumns['alphaId']]
  >
}

type _BetaRecordsIndexes = {
  readonly betaRecordsIdIdx: {
    readonly kind: 'index'
    readonly terms: readonly [_BetaRecordsColumns['id']]
    readonly unique: true
    readonly candidateKey: true
    readonly predicate: undefined
    readonly includedColumns?: readonly [_BetaRecordsColumns['alphaId']]
  }
}

type _BetaRecordsTable = _qubu.Table<
  'beta_records',
  typeof _BetaRecordsDefinitions,
  _BetaRecordsConstraints,
  _BetaRecordsIndexes
> & {
  readonly columns: _BetaRecordsColumns
}

export const betaRecords: _BetaRecordsTable = _qubu.table(
  'beta_records',
  _BetaRecordsDefinitions,
  _current => ({
    constraints: {
      betaRecordsAlphaFk: _qubu.catalogForeignKey(
        [_current.columns['alphaId']],
        () => _qubu.references(alphaRecords, alphaRecords.columns['id']),
        { physicalName: 'beta_records_alpha_fk' }
      ),
    },
    indexes: {
      betaRecordsIdIdx: _qubu.index([_current.columns['id']], {
        physicalName: 'beta_records_id_idx',
        unique: true,
        include: [_current.columns['alphaId']],
      }),
    },
  })
)

export const cycleDataSchema = _qubu.schema(
  {
    alphaRecords: alphaRecords,
    betaRecords: betaRecords,
  },
  { namespace: 'cycle_data' }
)
