/* Generated by Qubu. Do not edit this machine-owned file. */
import * as _qubu from 'qubu'

type _CatalogColumnOptions<TOutput, TInsert> = Omit<
  _qubu.ColumnOptions<TOutput, TInsert>,
  'storage'
> & {
  readonly storage?: never
}

const _catalogColumn =
  <
    TOutput = unknown,
    TInsert = unknown,
    TUpdate = unknown,
    TSqlType extends _qubu.AnySqlType = _qubu.SqlUnknown,
  >() =>
  <
    const TDialect extends string,
    const TDeclaration extends string,
    const TOptions extends _CatalogColumnOptions<TOutput, TInsert>,
  >(
    dialect: TDialect,
    declaration: TDeclaration,
    options: TOptions
  ) =>
    _qubu.nativeColumn<
      TOutput,
      TInsert,
      TUpdate,
      TOptions,
      TSqlType,
      TDialect,
      TDeclaration
    >(_qubu.nativeStorage(dialect, declaration), options)

const _catalogPredicate = <const TDialect extends _qubu.SchemaDialectName>(
  input: _qubu.CatalogCheckSql<TDialect>
) => _qubu.catalogCheck(input).expression

const _AccountEntriesDefinitions = {
  id: _catalogColumn<unknown, unknown, unknown, _qubu.SqlInteger>()(
    'postgresql',
    'integer',
    {
      nullable: false,
      sqlName: 'id',
    }
  ),
  parentId: _catalogColumn<unknown, unknown, unknown, _qubu.SqlInteger>()(
    'postgresql',
    'integer',
    {
      nullable: true,
      sqlName: 'parent_id',
      default: 0,
    }
  ),
  slug: _catalogColumn<unknown, unknown, unknown, _qubu.SqlText>()(
    'postgresql',
    'text',
    {
      nullable: false,
      sqlName: 'slug',
      generatedColumn: _qubu.generatedColumn(
        _qubu.unsafeSchemaSql({ dialect: 'postgresql', sql: 'lower(status)' }),
        'stored'
      ),
    }
  ),
  status: _catalogColumn<unknown, unknown, unknown, _qubu.SqlText>()(
    'postgresql',
    'text',
    {
      nullable: false,
      sqlName: 'status',
      default: 'pending',
    }
  ),
  updatedAt: _catalogColumn<unknown, unknown, unknown, _qubu.SqlTimestamp>()(
    'postgresql',
    'timestamp with time zone',
    {
      nullable: false,
      sqlName: 'updated_at',
      default: _qubu.unsafeSchemaSql({
        dialect: 'postgresql',
        sql: 'CURRENT_TIMESTAMP',
      }),
    }
  ),
}

type _AccountEntriesColumns = _qubu.TableColumns<
  typeof _AccountEntriesDefinitions,
  _qubu.TableIdentity<'account_entries'>
>

type _AccountEntriesConstraints = {
  readonly accountEntriesParentFk: _qubu.ForeignKeyConstraint<
    readonly [_AccountEntriesColumns['parentId']]
  >
  readonly accountEntriesParentKey: _qubu.UniqueConstraint<
    readonly [_AccountEntriesColumns['parentId']],
    'distinct'
  >
  readonly accountEntriesPkey: _qubu.KeyConstraint<
    'primary-key',
    readonly [_AccountEntriesColumns['id']]
  >
  readonly accountEntriesSlugKey: _qubu.KeyConstraint<
    'unique',
    readonly [_AccountEntriesColumns['slug']]
  >
  readonly accountEntriesStatusCheck: _qubu.CheckConstraint
}

type _AccountEntriesIndexes = {
  readonly accountEntriesSearchIdx: {
    readonly kind: 'index'
    readonly terms: readonly [
      _qubu.OrderTerm<unknown, _AccountEntriesColumns['parentId']>,
      _qubu.AnyExpression,
    ]
    readonly unique: false
    readonly candidateKey: false
    readonly predicate: _qubu.CatalogCheckExpression
    readonly includedColumns?: readonly [_AccountEntriesColumns['status']]
  }
}

type _AccountEntriesTable = _qubu.Table<
  'account_entries',
  typeof _AccountEntriesDefinitions,
  _AccountEntriesConstraints,
  _AccountEntriesIndexes
> & {
  readonly columns: _AccountEntriesColumns
}

export const accountEntries: _AccountEntriesTable = _qubu.table(
  'account_entries',
  _AccountEntriesDefinitions,
  _current => ({
    constraints: {
      accountEntriesParentFk: _qubu.catalogForeignKey(
        [_current.columns['parentId']],
        () => _qubu.references(parentRecords, parentRecords.columns['id']),
        {
          physicalName: 'account_entries_parent_fk',
          onUpdate: 'cascade',
          onDelete: 'set-null',
          match: 'full',
          deferrable: true,
          initially: 'deferred',
          dialect: { dialect: 'postgresql', ['notValid']: true },
        }
      ),
      accountEntriesParentKey: _qubu.uniqueConstraint(
        _current.columns['parentId'],
        { physicalName: 'account_entries_parent_key', nulls: 'distinct' }
      ),
      accountEntriesPkey: _qubu.primaryKey(_current.columns['id'], {
        physicalName: 'account_entries_pkey',
      }),
      accountEntriesSlugKey: _qubu.unique(_current.columns['slug'], {
        physicalName: 'account_entries_slug_key',
      }),
      accountEntriesStatusCheck: _qubu.catalogCheck(
        {
          dialect: 'postgresql',
          sql: "CHECK (status <> '*/\\nexport const hacked = true')",
        },
        { physicalName: 'account_entries_status_check' }
      ),
    },
    indexes: {
      accountEntriesSearchIdx: _qubu.index(
        [
          _qubu.order(_current.columns['parentId'], 'DESC', 'FIRST'),
          _qubu.unsafeSchemaSql({
            dialect: 'postgresql',
            sql: 'lower(status)',
          }),
        ],
        {
          physicalName: 'account_entries_search_idx',
          unique: false,
          where: _catalogPredicate({
            dialect: 'postgresql',
            sql: 'parent_id IS NOT NULL',
          }),
          include: [_current.columns['status']],
          dialect: { dialect: 'postgresql', ['method']: 'btree' },
        }
      ),
    },
  })
)

const _ParentRecordsDefinitions = {
  id: _catalogColumn<unknown, unknown, unknown, _qubu.SqlInteger>()(
    'postgresql',
    'integer',
    {
      nullable: false,
      sqlName: 'id',
      identity: _qubu.identityColumn('always', {
        dialect: { dialect: 'postgresql', ['sequenceOwned']: true },
      }),
    }
  ),
}

type _ParentRecordsColumns = _qubu.TableColumns<
  typeof _ParentRecordsDefinitions,
  _qubu.TableIdentity<'parent_records'>
>

type _ParentRecordsConstraints = {
  readonly parentRecordsPkey: _qubu.KeyConstraint<
    'primary-key',
    readonly [_ParentRecordsColumns['id']]
  >
}

type _ParentRecordsIndexes = {}

type _ParentRecordsTable = _qubu.Table<
  'parent_records',
  typeof _ParentRecordsDefinitions,
  _ParentRecordsConstraints,
  _ParentRecordsIndexes
> & {
  readonly columns: _ParentRecordsColumns
}

export const parentRecords: _ParentRecordsTable = _qubu.table(
  'parent_records',
  _ParentRecordsDefinitions,
  _current => ({
    constraints: {
      parentRecordsPkey: _qubu.primaryKey(_current.columns['id'], {
        physicalName: 'parent_records_pkey',
      }),
    },
    indexes: {},
  })
)

export const appDataSchema = _qubu.schema(
  {
    accountEntries: accountEntries,
    parentRecords: parentRecords,
  },
  { namespace: 'app_data' }
)
