import { readFileSync } from "node:fs"

import { format, resolveConfig } from "prettier"
import { expect, test } from "vitest"

import { generateSchemaSource } from "../src/codegen/index.ts"
import { mapCatalogToSnapshot } from "../src/introspection/index.ts"
import type {
  CatalogColumn,
  CatalogConstraint,
  CatalogDialect,
  IntrospectionCatalog,
  IntrospectionSuccess,
} from "../src/introspection/index.ts"
import { createPostgresSchemaSnapshot, createSqliteSchemaSnapshot } from "../src/snapshot/index.ts"
import type {
  SchemaSnapshot,
  SnapshotConstraint,
  SnapshotIndexTerm,
} from "../src/snapshot/index.ts"
import { cycleDataSchema } from "./codegen-cycle.generated.ts"
import { emptyDataSchema } from "./codegen-empty.generated.ts"
import {
  codegenCatalog,
  codegenInput,
  cycleCodegenInput,
  emptyCodegenInput,
  sqliteCodegenInput,
} from "./codegen-fixtures.ts"
import { appDataSchema } from "./codegen-rich.generated.ts"
import { mainSchema } from "./codegen-sqlite.generated.ts"

const prettierConfig = await resolveConfig(new URL("../package.json", import.meta.url).pathname)

test("generates deterministic escaped source for complete Snapshot v1 facts", () => {
  const first = generateSchemaSource(codegenInput)
  const second = generateSchemaSource(codegenInput)

  expect(first).toEqual(second)
  expect(first.ok).toBe(true)
  if (!first.ok) {
    return
  }

  expect(first.source).toContain("export const accountEntries: _AccountEntriesTable = _qubu.table(")
  expect(first.source).toContain("export const parentRecords: _ParentRecordsTable = _qubu.table(")
  expect(first.source).toContain("export const appDataSchema = _qubu.schema(")
  expect(first.source).toContain("_qubu.catalogCheck(")
  expect(first.source).toContain("_qubu.catalogForeignKey(")
  expect(first.source).toContain(
    '() => _qubu.references(parentRecords, parentRecords.columns["id"])',
  )
  expect(first.source).toContain("generatedColumn: _qubu.generatedColumn(")
  expect(first.source).toContain('include: [_current.columns["status"]]')
  expect(first.source).toContain("where: _catalogPredicate(")
  expect(first.source).not.toContain("\nexport const hacked = true")
  expect(first.source.match(/Generated by Qubu/g)).toHaveLength(1)
  expect(first.source).not.toMatch(/\sas\s+(?:const|unknown|[A-Z])/)
  expect(first.diagnostics).toEqual(
    expect.arrayContaining([
      expect.objectContaining({ code: "unmodeled-object" }),
      expect.objectContaining({
        code: "excluded-object-family",
        path: ["catalog", "deferredObjects"],
      }),
    ]),
  )
})

test("applies controlled naming and column type mappings", () => {
  const result = generateSchemaSource(codegenInput, {
    naming(context) {
      if (context.kind === "schema") {
        return "applicationSchema"
      }

      if (context.kind === "column" && context.physicalName === "parent_id") {
        return "ownerId"
      }
    },
    mapColumn(context) {
      if (context.columnPhysicalName === "status") {
        return {
          output: "string",
          insert: "string",
          update: "string",
          sqlDomain: "text",
        }
      }
    },
  })

  expect(result.ok).toBe(true)
  if (!result.ok) {
    return
  }

  expect(result.source).toContain("export const applicationSchema")
  expect(result.source).toContain('"ownerId": _catalogColumn<')
  expect(result.source).toContain(
    '"status": _catalogColumn<string, string, string, _qubu.SqlText>()',
  )
})

test("infers SQL domains only from exact native declarations", () => {
  const cases = [
    ["postgresql", "integer", "_qubu.SqlInteger"],
    ["postgresql", "int4", "_qubu.SqlUnknown"],
    ["postgresql", "numeric(10, 2)", "_qubu.SqlUnknown"],
    ["mysql", "int", "_qubu.SqlInteger"],
    ["mysql", "integer", "_qubu.SqlUnknown"],
    ["sqlite", "INTEGER", "_qubu.SqlUnknown"],
  ] as const

  for (const [dialect, declaration, sqlDomain] of cases) {
    const result = generateSchemaSource(nativeTypeInput(dialect, declaration))

    expect(result.ok).toBe(true)
    if (!result.ok) {
      continue
    }

    expect(result.source).toContain(`_catalogColumn<unknown, unknown, unknown, ${sqlDomain}>()`)
  }
})

test("returns diagnostics without source for lossy input and name collisions", () => {
  const lossy = generateSchemaSource({
    ...codegenInput,
    lossy: true,
  })

  expect(lossy.ok).toBe(false)
  expect(lossy).not.toHaveProperty("source")
  if (!lossy.ok) {
    expect(lossy.diagnostics).toEqual(
      expect.arrayContaining([expect.objectContaining({ code: "lossy-input" })]),
    )
  }

  const collision = generateSchemaSource(codegenInput, {
    naming(context) {
      if (context.kind === "table") {
        return "records"
      }
    },
  })

  expect(collision.ok).toBe(false)
  expect(collision).not.toHaveProperty("source")
  if (!collision.ok) {
    expect(collision.diagnostics).toEqual(
      expect.arrayContaining([expect.objectContaining({ code: "name-collision" })]),
    )
  }

  const unsafe = generateSchemaSource(codegenInput, {
    naming(context) {
      if (context.kind === "table") {
        return "not-source-safe"
      }
    },
  })

  expect(unsafe.ok).toBe(false)
  expect(unsafe).not.toHaveProperty("source")
  if (!unsafe.ok) {
    expect(unsafe.diagnostics).toEqual(
      expect.arrayContaining([expect.objectContaining({ code: "unsafe-name" })]),
    )
  }
})

test("rejects strict-mode reserved export bindings from defaults and callbacks", () => {
  const strictBindings = [
    "arguments",
    "eval",
    "implements",
    "interface",
    "package",
    "private",
    "protected",
    "public",
  ] as const

  for (const binding of strictBindings) {
    const fromDefault = generateSchemaSource(nativeTypeInput("postgresql", "integer", binding))

    expect(fromDefault.ok).toBe(false)
    expect(fromDefault).not.toHaveProperty("source")
    if (!fromDefault.ok) {
      expect(fromDefault.diagnostics).toEqual(
        expect.arrayContaining([expect.objectContaining({ code: "unsafe-name" })]),
      )
    }

    const fromCallback = generateSchemaSource(nativeTypeInput("postgresql", "integer"), {
      naming(context) {
        return context.kind === "table" ? binding : undefined
      },
    })

    expect(fromCallback.ok).toBe(false)
    expect(fromCallback).not.toHaveProperty("source")
    if (!fromCallback.ok) {
      expect(fromCallback.diagnostics).toEqual(
        expect.arrayContaining([expect.objectContaining({ code: "unsafe-name" })]),
      )
    }
  }
})

test("generates a reader-normalized PostgreSQL generated column without a default", () => {
  const input = nativeTypeInput("postgresql", "text", "generated_records", {
    generated: {
      kind: "generated",
      mode: "stored",
      expression: {
        kind: "sql",
        dialect: "postgresql",
        text: "lower(value)",
        provenance: {
          kind: "catalog",
          dialect: "postgresql",
        },
      },
    },
  })
  const column = input.snapshot.tables[0]?.columns[0]

  expect(column).toMatchObject({
    hasDefault: false,
    generated: true,
    generatedColumn: { mode: "stored" },
  })
  expect(column?.default).toBeUndefined()

  const generated = generateSchemaSource(input)

  expect(generated.ok).toBe(true)
  if (!generated.ok) {
    return
  }

  expect(generated.source).toContain("generatedColumn: _qubu.generatedColumn(")
  expect(generated.source).not.toContain("default:")
})

test("returns diagnostics when a customization callback throws", () => {
  const result = generateSchemaSource(codegenInput, {
    naming() {
      throw new Error("mapping failed")
    },
  })

  expect(result.ok).toBe(false)
  expect(result).not.toHaveProperty("source")
  if (!result.ok) {
    expect(result.diagnostics).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          code: "invalid-option",
          message: expect.stringContaining("mapping failed"),
        }),
      ]),
    )
  }
})

test("rejects a snapshot that omits catalog table facts", () => {
  const malformed: IntrospectionSuccess = {
    ...codegenInput,
    snapshot: {
      ...codegenInput.snapshot,
      tables: codegenInput.snapshot.tables.slice(1),
    },
  }
  const result = generateSchemaSource(malformed)

  expect(result.ok).toBe(false)
  expect(result).not.toHaveProperty("source")
  if (!result.ok) {
    expect(result.diagnostics).toEqual(
      expect.arrayContaining([expect.objectContaining({ code: "omitted-fact" })]),
    )
  }
})

test("rejects generated key proofs that TypeScript cannot satisfy", () => {
  const cases = [
    ["nullable-unique-target", "does not target an exact"],
    ["unequal-arity", "unequal local and target arity"],
    ["unmatched-target", "does not target an exact"],
    ["nullable-primary", "contains nullable columns"],
  ] as const

  for (const [kind, message] of cases) {
    const result = generateSchemaSource(invalidProofInput(kind))

    expect(result.ok).toBe(false)
    expect(result).not.toHaveProperty("source")
    if (!result.ok) {
      expect(result.diagnostics).toEqual(
        expect.arrayContaining([
          expect.objectContaining({
            code: "unrepresentable-fact",
            message: expect.stringContaining(message),
          }),
        ]),
      )
    }
  }
})

test("retains excluded-family diagnostics from a failed introspection result", () => {
  const result = generateSchemaSource({
    ok: false,
    catalog: codegenCatalog,
    diagnostics: codegenCatalog.diagnostics,
    lossy: false,
  })

  expect(result.ok).toBe(false)
  if (!result.ok) {
    expect(result.diagnostics.map((issue) => issue.code)).toEqual([
      "unmodeled-object",
      "excluded-object-family",
      "invalid-input",
    ])
  }
})

test("matches compiled generated fixtures without source assertions", async () => {
  const fixtures = [
    [codegenInput, "codegen-rich.generated.ts"],
    [cycleCodegenInput, "codegen-cycle.generated.ts"],
    [emptyCodegenInput, "codegen-empty.generated.ts"],
    [sqliteCodegenInput, "codegen-sqlite.generated.ts"],
  ] as const

  for (const [input, fileName] of fixtures) {
    const result = generateSchemaSource(input)

    expect(result.ok).toBe(true)
    if (!result.ok) {
      continue
    }

    const expected = readFileSync(new URL(fileName, import.meta.url), "utf8")
    const formatted = await format(result.source, {
      ...prettierConfig,
      parser: "typescript",
    })

    expect(formatted).toBe(expected)
    expect(expected.replace("import * as _qubu from 'qubu'", "")).not.toMatch(
      /\b(?:as|satisfies)\b/u,
    )
  }
})

test("compiles an empty generated schema without unused helper declarations", () => {
  const generated = generateSchemaSource(emptyCodegenInput)

  expect(generated.ok).toBe(true)
  if (!generated.ok) {
    return
  }

  expect(generated.source).not.toContain("_CatalogColumnOptions")
  expect(generated.source).not.toContain("_catalogColumn")
  expect(createPostgresSchemaSnapshot(emptyDataSchema).tables).toEqual([])
})

test("round-trips generated SQLite native declarations and derived affinity", () => {
  const generated = createSqliteSchemaSnapshot(mainSchema)
  const storage = sqliteCodegenInput.snapshot.tables
    .find((table) => table.physicalName === "sqlite_records")
    ?.columns.find((column) => column.physicalName === "record_id")?.storage

  expect(storage).toEqual({
    kind: "native",
    dialect: "sqlite",
    type: "INTEGER",
    affinity: "integer",
  })
  expect(physicalFacts(generated)).toEqual(physicalFacts(sqliteCodegenInput.snapshot))
})

test("round-trips representative physical Snapshot v1 table facts", () => {
  const generated = createPostgresSchemaSnapshot(appDataSchema)

  expect(physicalFacts(generated)).toEqual(physicalFacts(codegenInput.snapshot))
})

test("resolves forward and cyclic generated foreign-key targets lazily", () => {
  const forward = createPostgresSchemaSnapshot(appDataSchema)
  const cycle = createPostgresSchemaSnapshot(cycleDataSchema)

  expect(
    forward.tables
      .find((table) => table.physicalName === "account_entries")
      ?.constraints.find((constraint) => constraint.kind === "foreign-key"),
  ).toMatchObject({
    target: {
      table: "parentRecords",
      columns: ["id"],
    },
  })
  expect(
    cycle.tables.map((table) =>
      table.constraints.find((constraint) => constraint.kind === "foreign-key"),
    ),
  ).toEqual([
    expect.objectContaining({
      target: {
        table: "betaRecords",
        columns: ["id"],
      },
    }),
    expect.objectContaining({
      target: {
        table: "alphaRecords",
        columns: ["id"],
      },
    }),
  ])
})

function physicalFacts(snapshot: SchemaSnapshot): unknown {
  const tablesById = new Map(snapshot.tables.map((table) => [table.id, table]))
  const columnsByTable = new Map(
    snapshot.tables.map((table) => [
      table.id,
      new Map(table.columns.map((column) => [column.id, column.physicalName])),
    ]),
  )

  return {
    dialect: snapshot.dialect,
    namespace: snapshot.namespace,
    tables: [...snapshot.tables].sort(comparePhysical).map((table) => ({
      physicalName: table.physicalName,
      columns: [...table.columns].sort(comparePhysical).map((column) => {
        const { id: _id, ...facts } = column

        void _id
        return facts
      }),
      constraints: [...table.constraints]
        .sort(comparePhysical)
        .map((constraint) => physicalConstraint(constraint, table.id, tablesById, columnsByTable)),
      indexes: [...table.indexes].sort(comparePhysical).map((index) => {
        const { id: _id, ...facts } = index

        void _id
        const columns = columnsByTable.get(table.id)

        return {
          ...facts,
          terms: index.terms.map((term) => physicalIndexTerm(term, columns)),
          includedColumns: index.includedColumns?.map(
            (column) => columns?.get(column) ?? `missing:${column}`,
          ),
        }
      }),
    })),
  }
}

function physicalConstraint(
  constraint: SnapshotConstraint,
  tableId: string,
  tables: ReadonlyMap<string, SchemaSnapshot["tables"][number]>,
  columns: ReadonlyMap<string, ReadonlyMap<string, string>>,
): unknown {
  const { id: _id, ...facts } = constraint

  void _id
  if (constraint.kind === "check") {
    return facts
  }

  const local = constraint.columns.map(
    (column) => columns.get(tableId)?.get(column) ?? `missing:${column}`,
  )

  if (constraint.kind !== "foreign-key") {
    return {
      ...facts,
      columns: local,
    }
  }

  return {
    ...facts,
    columns: local,
    target: {
      table:
        tables.get(constraint.target.table)?.physicalName ?? `missing:${constraint.target.table}`,
      columns: constraint.target.columns.map(
        (column) => columns.get(constraint.target.table)?.get(column) ?? `missing:${column}`,
      ),
    },
  }
}

function physicalIndexTerm(
  term: SnapshotIndexTerm,
  columns: ReadonlyMap<string, string> | undefined,
): unknown {
  if (term.kind === "column") {
    return {
      ...term,
      column: columns?.get(term.column) ?? `missing:${term.column}`,
    }
  }

  if (term.kind === "expression") {
    return term
  }

  return {
    ...term,
    expression:
      term.expression.kind === "column"
        ? {
            ...term.expression,
            column: columns?.get(term.expression.column) ?? `missing:${term.expression.column}`,
          }
        : term.expression,
  }
}

function comparePhysical(
  left: { readonly physicalName: string },
  right: { readonly physicalName: string },
): number {
  return left.physicalName.localeCompare(right.physicalName)
}

function nativeTypeInput(
  dialect: CatalogDialect,
  declaration: string,
  tablePhysicalName = "records",
  facts: Partial<CatalogColumn> = {},
): IntrospectionSuccess {
  const namespace = dialect === "sqlite" ? "main" : "app_data"
  const catalog: IntrospectionCatalog = {
    dialect,
    server: {
      ...codegenCatalog.server,
      product: dialect === "postgresql" ? "PostgreSQL" : dialect === "mysql" ? "MySQL" : "SQLite",
    },
    namespace: {
      kind:
        dialect === "postgresql"
          ? "postgres-schema"
          : dialect === "mysql"
            ? "mysql-database"
            : "sqlite-database",
      name: namespace,
    },
    tables: [
      {
        kind: "table",
        id: tablePhysicalName,
        identitySource: "physical-name",
        physicalName: tablePhysicalName,
        columns: [
          {
            kind: "column",
            id: "value",
            identitySource: "physical-name",
            physicalName: "value",
            ordinalPosition: 1,
            nullable: false,
            storage: { nativeType: declaration },
            ...facts,
          },
        ],
        constraints: [],
        indexes: [],
      },
    ],
    deferredObjects: [],
    diagnostics: [],
  }
  const result = mapCatalogToSnapshot(catalog, { namespace })

  if (!result.ok) {
    throw new Error(result.diagnostics.map((issue) => issue.message).join("\n"))
  }

  return result
}

function invalidProofInput(
  kind: "nullable-unique-target" | "unequal-arity" | "unmatched-target" | "nullable-primary",
): IntrospectionSuccess {
  const targetColumns =
    kind === "unequal-arity"
      ? [proofColumn("part_a"), proofColumn("part_b")]
      : kind === "unmatched-target"
        ? [proofColumn("id"), proofColumn("code")]
        : [proofColumn("id", true)]
  const keyColumns = kind === "unequal-arity" ? ["part_a", "part_b"] : ["id"]
  const targetKey: CatalogConstraint =
    kind === "nullable-unique-target"
      ? {
          kind: "unique",
          id: "parent_records_key",
          identitySource: "physical-name",
          physicalName: "parent_records_key",
          columns: keyColumns,
          nulls: "distinct",
        }
      : {
          kind: "primary-key",
          id: "parent_records_key",
          identitySource: "physical-name",
          physicalName: "parent_records_key",
          columns: keyColumns,
        }
  const parent = {
    kind: "table" as const,
    id: "parent_records",
    identitySource: "physical-name" as const,
    physicalName: "parent_records",
    columns: targetColumns,
    constraints: [targetKey],
    indexes: [],
  }
  const tables: IntrospectionCatalog["tables"] =
    kind === "nullable-primary"
      ? [parent]
      : [
          parent,
          {
            kind: "table",
            id: "child_records",
            identitySource: "physical-name",
            physicalName: "child_records",
            columns: [proofColumn("parent_id")],
            constraints: [
              {
                kind: "foreign-key",
                id: "child_records_parent_fk",
                identitySource: "physical-name",
                physicalName: "child_records_parent_fk",
                columns: ["parent_id"],
                target: {
                  table: "parent_records",
                  columns:
                    kind === "unequal-arity"
                      ? ["part_a", "part_b"]
                      : kind === "unmatched-target"
                        ? ["code"]
                        : ["id"],
                },
              },
            ],
            indexes: [],
          },
        ]
  const catalog: IntrospectionCatalog = {
    ...codegenCatalog,
    namespace: {
      kind: "postgres-schema",
      name: "proof_data",
    },
    tables,
    deferredObjects: [],
    diagnostics: [],
  }
  const result = mapCatalogToSnapshot(catalog, { namespace: "proof_data" })

  if (!result.ok) {
    throw new Error(result.diagnostics.map((issue) => issue.message).join("\n"))
  }

  return result
}

function proofColumn(physicalName: string, nullable = false): CatalogColumn {
  return {
    kind: "column",
    id: physicalName,
    identitySource: "physical-name",
    physicalName,
    ordinalPosition: 1,
    nullable,
    storage: { nativeType: "integer" },
  }
}
