/* Generated by Qubu. Do not edit this machine-owned file. */
import * as _qubu from 'qubu'

type _CatalogColumnOptions = Omit<_qubu.ColumnOptions, 'storage'> & {
  readonly storage?: never
}

const _catalogColumn =
  <
    TOutput = unknown,
    TInsert = unknown,
    TUpdate = unknown,
    TSqlType extends _qubu.AnySqlType = _qubu.SqlUnknown,
  >() =>
  <
    const TDialect extends string,
    const TDeclaration extends string,
    const TOptions extends _CatalogColumnOptions,
  >(
    dialect: TDialect,
    declaration: TDeclaration,
    options: TOptions
  ) =>
    _qubu.nativeColumn<
      TOutput,
      TInsert,
      TUpdate,
      TOptions,
      TSqlType,
      TDialect,
      TDeclaration
    >(_qubu.nativeStorage(dialect, declaration), options)

const _EmptyRecordsDefinitions = {}

type _EmptyRecordsColumns = _qubu.TableColumns<
  typeof _EmptyRecordsDefinitions,
  _qubu.TableIdentity<'empty_records'>
>

type _EmptyRecordsConstraints = {}

type _EmptyRecordsIndexes = {}

type _EmptyRecordsTable = _qubu.Table<
  'empty_records',
  typeof _EmptyRecordsDefinitions,
  _EmptyRecordsConstraints,
  _EmptyRecordsIndexes
> & {
  readonly columns: _EmptyRecordsColumns
}

export const emptyRecords: _EmptyRecordsTable = _qubu.table(
  'empty_records',
  _EmptyRecordsDefinitions,
  _current => ({
    constraints: {},
    indexes: {},
  })
)

const _SqliteRecordsDefinitions = {
  recordId: _catalogColumn<unknown, unknown, unknown, _qubu.SqlUnknown>()(
    'sqlite',
    'INTEGER',
    {
      nullable: false,
      sqlName: 'record_id',
    }
  ),
}

type _SqliteRecordsColumns = _qubu.TableColumns<
  typeof _SqliteRecordsDefinitions,
  _qubu.TableIdentity<'sqlite_records'>
>

type _SqliteRecordsConstraints = {}

type _SqliteRecordsIndexes = {}

type _SqliteRecordsTable = _qubu.Table<
  'sqlite_records',
  typeof _SqliteRecordsDefinitions,
  _SqliteRecordsConstraints,
  _SqliteRecordsIndexes
> & {
  readonly columns: _SqliteRecordsColumns
}

export const sqliteRecords: _SqliteRecordsTable = _qubu.table(
  'sqlite_records',
  _SqliteRecordsDefinitions,
  _current => ({
    constraints: {},
    indexes: {},
  })
)

export const mainSchema = _qubu.schema(
  {
    emptyRecords: emptyRecords,
    sqliteRecords: sqliteRecords,
  },
  { namespace: 'main' }
)
