import type {
  SnapshotConstraint,
  SnapshotDialectExtension,
  SnapshotExpression,
  SnapshotIndexTerm,
  SnapshotIndexTermExpression,
  SnapshotJsonValue,
  SnapshotLiteral,
} from "../snapshot/types.ts"
import type {
  ResolvedColumn,
  ResolvedConstraint,
  ResolvedIndex,
  ResolvedSchema,
  ResolvedTable,
} from "./model.ts"
import type { CodegenApplicationType, CodegenDiagnostic, CodegenSqlDomain } from "./types.ts"

const header = `/* Generated by Qubu. Do not edit this machine-owned file. */
import * as _qubu from 'qubu'
`

const catalogColumnHelper = `type _CatalogColumnOptions = Omit<_qubu.ColumnOptions, 'storage'> & {
  readonly storage?: never
}

const _catalogColumn = <
  TOutput = unknown,
  TInsert = unknown,
  TUpdate = unknown,
  TSqlType extends _qubu.AnySqlType = _qubu.SqlUnknown,
>() =>
  <
    const TDialect extends string,
    const TDeclaration extends string,
    const TOptions extends _CatalogColumnOptions,
  >(
    dialect: TDialect,
    declaration: TDeclaration,
    options: TOptions
  ) =>
    _qubu.nativeColumn<
      TOutput,
      TInsert,
      TUpdate,
      TOptions,
      TSqlType,
      TDialect,
      TDeclaration
    >(_qubu.nativeStorage(dialect, declaration), options)
`

const catalogPredicateHelper = `const _catalogPredicate = <
  const TDialect extends _qubu.SchemaDialectName,
>(input: _qubu.CatalogCheckSql<TDialect>) =>
  _qubu.catalogCheck(input).expression
`

export function printSchemaSource(
  schema: ResolvedSchema,
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const tables = schema.tables.map((table) => printTable(schema, table, diagnostics))

  if (tables.some((table) => table === undefined)) {
    return undefined
  }

  const registry = schema.tables
    .map((table) => `    ${literal(table.name)}: ${table.name},`)
    .join("\n")
  const predicateHelper = schema.tables.some((table) =>
    table.indexes.some((index) => index.snapshot.predicate !== undefined),
  )
    ? `\n${catalogPredicateHelper}`
    : ""
  const columnHelper = schema.tables.some((table) => table.columns.length > 0)
    ? `\n${catalogColumnHelper}`
    : ""

  return `${header}${columnHelper}${predicateHelper}\n${tables.join("\n\n")}\n\nexport const ${schema.name} = _qubu.schema(\n  {\n${registry}\n  },\n  { namespace: ${literal(schema.namespace)} }\n)\n`
}

function printTable(
  schema: ResolvedSchema,
  table: ResolvedTable,
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const columns = table.columns.map((column) => printColumn(schema, table, column, diagnostics))
  const constraints = table.constraints.map((constraint) =>
    printConstraint(schema, table, constraint, diagnostics),
  )
  const indexes = table.indexes.map((index) => printIndex(schema, table, index, diagnostics))

  if (
    columns.some((value) => value === undefined) ||
    constraints.some((value) => value === undefined) ||
    indexes.some((value) => value === undefined)
  ) {
    return undefined
  }

  const typePrefix = `_${capitalize(table.name)}`
  const definitionsName = `${typePrefix}Definitions`
  const columnsName = `${typePrefix}Columns`
  const constraintsName = `${typePrefix}Constraints`
  const indexesName = `${typePrefix}Indexes`
  const tableTypeName = `${typePrefix}Table`
  const constraintTypes = table.constraints.map((constraint) =>
    printConstraintType(table, constraint, columnsName, diagnostics),
  )
  const indexTypes = table.indexes.map((index) =>
    printIndexType(table, index, columnsName, diagnostics),
  )

  if (
    constraintTypes.some((value) => value === undefined) ||
    indexTypes.some((value) => value === undefined)
  ) {
    return undefined
  }

  return `const ${definitionsName} = {
${columns.map((value) => indent(value ?? "", 2)).join("\n")}
}

type ${columnsName} = _qubu.TableColumns<
  typeof ${definitionsName},
  _qubu.TableIdentity<${literal(table.snapshot.physicalName)}>
>

type ${constraintsName} = {
${constraintTypes.map((value) => indent(value ?? "", 2)).join("\n")}
}

type ${indexesName} = {
${indexTypes.map((value) => indent(value ?? "", 2)).join("\n")}
}

type ${tableTypeName} = _qubu.Table<
  ${literal(table.snapshot.physicalName)},
  typeof ${definitionsName},
  ${constraintsName},
  ${indexesName}
> & {
  readonly columns: ${columnsName}
}

export const ${table.name}: ${tableTypeName} = _qubu.table(
  ${literal(table.snapshot.physicalName)},
  ${definitionsName},
  _current => ({
    constraints: {
${constraints.map((value) => indent(value ?? "", 6)).join("\n")}
    },
    indexes: {
${indexes.map((value) => indent(value ?? "", 6)).join("\n")}
    },
  })
)`
}

function printConstraintType(
  table: ResolvedTable,
  constraint: ResolvedConstraint,
  columnsName: string,
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const snapshot = constraint.snapshot
  const path = ["snapshot", "tables", table.snapshot.id, "constraints", snapshot.id] as const

  if (snapshot.kind === "check") {
    return `readonly ${literal(constraint.name)}: _qubu.CheckConstraint`
  }

  const columns = printColumnTypeTuple(table, snapshot.columns, columnsName, path, diagnostics)

  if (columns === undefined) {
    return undefined
  }

  if (snapshot.kind === "foreign-key") {
    return `readonly ${literal(constraint.name)}: _qubu.ForeignKeyConstraint<${columns}>`
  }

  if (snapshot.kind === "unique-constraint") {
    return `readonly ${literal(constraint.name)}: _qubu.UniqueConstraint<
  ${columns},
  ${literal(snapshot.nulls)}
>`
  }

  return `readonly ${literal(constraint.name)}: _qubu.KeyConstraint<
  ${literal(snapshot.kind)},
  ${columns}
>`
}

function printIndexType(
  table: ResolvedTable,
  index: ResolvedIndex,
  columnsName: string,
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const path = ["snapshot", "tables", table.snapshot.id, "indexes", index.snapshot.id] as const
  const terms = index.snapshot.terms.map((term, position) =>
    printIndexTermType(table, term, columnsName, [...path, "terms", position], diagnostics),
  )

  if (terms.some((term) => term === undefined)) {
    return undefined
  }

  const properties = [
    `readonly terms: readonly [${terms.join(", ")}]`,
    `readonly unique: ${index.snapshot.unique ? "true" : "false"}`,
    `readonly candidateKey: ${index.snapshot.candidateKey ? "true" : "false"}`,
    `readonly predicate: ${index.snapshot.predicate === undefined ? "undefined" : "_qubu.CatalogCheckExpression"}`,
  ]

  if (index.snapshot.includedColumns !== undefined) {
    const included = printColumnTypeTuple(
      table,
      index.snapshot.includedColumns,
      columnsName,
      [...path, "includedColumns"],
      diagnostics,
    )

    if (included === undefined) {
      return undefined
    }

    properties.push(`readonly includedColumns?: ${included}`)
  } else {
    properties.push("readonly includedColumns?: undefined")
  }

  return `readonly ${literal(index.name)}: {
  readonly kind: 'index'
${properties.map((property) => `  ${property}`).join("\n")}
}`
}

function printIndexTermType(
  table: ResolvedTable,
  term: SnapshotIndexTerm,
  columnsName: string,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  if (term.kind !== "order") {
    return printIndexTermExpressionType(table, term, columnsName, path, diagnostics)
  }

  const expression = printIndexTermExpressionType(
    table,
    term.expression,
    columnsName,
    [...path, "expression"],
    diagnostics,
  )

  return expression === undefined ? undefined : `_qubu.OrderTerm<unknown, ${expression}>`
}

function printIndexTermExpressionType(
  table: ResolvedTable,
  expression: SnapshotIndexTermExpression,
  columnsName: string,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  if (expression.kind === "expression") {
    return "_qubu.AnyExpression"
  }

  const column = table.columnsBySnapshotId.get(expression.column)

  if (column === undefined) {
    diagnostics.push(
      sourceError(`Index column "${expression.column}" was not resolved`, [...path, "column"]),
    )
    return undefined
  }

  return `${columnsName}[${literal(column.name)}]`
}

function printColumnTypeTuple(
  table: ResolvedTable,
  ids: readonly string[],
  columnsName: string,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const columns: string[] = []

  for (const [position, id] of ids.entries()) {
    const column = table.columnsBySnapshotId.get(id)

    if (column === undefined) {
      diagnostics.push(
        sourceError(`Column "${id}" was not resolved`, [...path, "columns", position]),
      )
      continue
    }

    columns.push(`${columnsName}[${literal(column.name)}]`)
  }

  return columns.length === ids.length && columns.length > 0
    ? `readonly [${columns.join(", ")}]`
    : undefined
}

function printColumn(
  schema: ResolvedSchema,
  table: ResolvedTable,
  column: ResolvedColumn,
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const path = ["snapshot", "tables", table.snapshot.id, "columns", column.snapshot.id] as const
  const snapshot = column.snapshot

  if (snapshot.storage?.kind !== "native") {
    diagnostics.push(sourceError("Generated columns require native storage", [...path, "storage"]))
    return undefined
  }

  const options: string[] = [
    `nullable: ${snapshot.nullable ? "true" : "false"}`,
    `sqlName: ${literal(snapshot.physicalName)}`,
  ]

  if (snapshot.default !== undefined) {
    if (snapshot.default.kind === "external") {
      options.push("default: _qubu.externalDefault()")
    } else if (snapshot.default.kind === "literal") {
      const value = printSnapshotLiteral(snapshot.default.value, path, diagnostics)

      if (value === undefined) {
        return undefined
      }

      options.push(`default: ${value}`)
    } else {
      const value = printExpression(
        snapshot.default.expression,
        schema,
        [...path, "default", "expression"],
        diagnostics,
      )

      if (value === undefined) {
        return undefined
      }

      options.push(`default: ${value}`)
    }
  }

  if (snapshot.generatedColumn !== undefined) {
    if (snapshot.generatedColumn.kind === "external") {
      options.push("generatedColumn: _qubu.externalGeneratedColumn()")
    } else {
      const expression = printExpression(
        snapshot.generatedColumn.expression,
        schema,
        [...path, "generatedColumn", "expression"],
        diagnostics,
      )

      if (expression === undefined) {
        return undefined
      }

      options.push(
        `generatedColumn: _qubu.generatedColumn(${expression}, ${literal(snapshot.generatedColumn.mode)})`,
      )
    }
  }

  if (snapshot.identity !== undefined) {
    const extension = snapshot.identity.dialect
      ? printExtension(
          snapshot.identity.dialect,
          schema,
          [...path, "identity", "dialect"],
          diagnostics,
        )
      : undefined

    if (snapshot.identity.dialect !== undefined && extension === undefined) {
      return undefined
    }

    options.push(
      extension === undefined
        ? `identity: _qubu.identityColumn(${literal(snapshot.identity.generation)})`
        : `identity: _qubu.identityColumn(${literal(snapshot.identity.generation)}, { dialect: ${extension} })`,
    )
  }

  if (snapshot.onUpdate !== undefined) {
    const expression = printExpression(
      snapshot.onUpdate,
      schema,
      [...path, "onUpdate"],
      diagnostics,
    )

    if (expression === undefined) {
      return undefined
    }

    options.push(`onUpdate: ${expression}`)
  }

  const types = [
    applicationType(column.output),
    applicationType(column.insert),
    applicationType(column.update),
    sqlDomainType(column.sqlDomain),
  ].join(", ")
  const optionSource = `{
${options.map((option) => `  ${option},`).join("\n")}
}`

  return `${literal(column.name)}: _catalogColumn<${types}>()(
  ${literal(snapshot.storage.dialect)},
  ${literal(snapshot.storage.type)},
${indent(optionSource, 2)}
),`
}

function printConstraint(
  schema: ResolvedSchema,
  table: ResolvedTable,
  constraint: ResolvedConstraint,
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const snapshot = constraint.snapshot
  const path = ["snapshot", "tables", table.snapshot.id, "constraints", snapshot.id] as const
  const options = printConstraintOptions(snapshot, schema, path, diagnostics)

  if (options === undefined) {
    return undefined
  }

  let expression: string | undefined

  if (snapshot.kind === "check") {
    const sql = catalogExpressionData(
      snapshot.expression,
      schema,
      [...path, "expression"],
      diagnostics,
    )

    if (sql === undefined) {
      return undefined
    }

    expression = `_qubu.catalogCheck(${sql}, ${options})`
  } else if (snapshot.kind === "foreign-key") {
    const local = printColumns(table, snapshot.columns, path, diagnostics)
    const targetTable = schema.tablesBySnapshotId.get(snapshot.target.table)

    if (targetTable === undefined) {
      diagnostics.push(
        sourceError(`Foreign-key target table "${snapshot.target.table}" was not resolved`, [
          ...path,
          "target",
          "table",
        ]),
      )
      return undefined
    }

    const target = printColumns(
      targetTable,
      snapshot.target.columns,
      [...path, "target"],
      diagnostics,
      targetTable.name,
    )

    if (local === undefined || target === undefined) {
      return undefined
    }

    expression = `_qubu.catalogForeignKey(
  [${local.join(", ")}],
  () => _qubu.references(${targetTable.name}, ${target.join(", ")}),
  ${options}
)`
  } else {
    const columns = printColumns(table, snapshot.columns, path, diagnostics)

    if (columns === undefined) {
      return undefined
    }

    const helper =
      snapshot.kind === "primary-key"
        ? "primaryKey"
        : snapshot.kind === "unique"
          ? "unique"
          : "uniqueConstraint"

    expression = `_qubu.${helper}(${columns.join(", ")}, ${options})`
  }

  return `${literal(constraint.name)}: ${expression},`
}

function printConstraintOptions(
  constraint: SnapshotConstraint,
  schema: ResolvedSchema,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const properties = [`physicalName: ${literal(constraint.physicalName)}`]

  if (constraint.kind === "unique-constraint") {
    properties.push(`nulls: ${literal(constraint.nulls)}`)
  }

  if (constraint.kind === "foreign-key") {
    if (constraint.onUpdate !== undefined) {
      properties.push(`onUpdate: ${literal(constraint.onUpdate)}`)
    }

    if (constraint.onDelete !== undefined) {
      properties.push(`onDelete: ${literal(constraint.onDelete)}`)
    }

    if (constraint.match !== undefined) {
      properties.push(`match: ${literal(constraint.match)}`)
    }
  }

  if (constraint.deferrable !== undefined) {
    properties.push(`deferrable: ${constraint.deferrable ? "true" : "false"}`)
  }

  if (constraint.initially !== undefined) {
    properties.push(`initially: ${literal(constraint.initially)}`)
  }

  if (constraint.dialect !== undefined) {
    const extension = printExtension(constraint.dialect, schema, [...path, "dialect"], diagnostics)

    if (extension === undefined) {
      return undefined
    }

    properties.push(`dialect: ${extension}`)
  }

  return `{ ${properties.join(", ")} }`
}

function printIndex(
  schema: ResolvedSchema,
  table: ResolvedTable,
  index: ResolvedIndex,
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const path = ["snapshot", "tables", table.snapshot.id, "indexes", index.snapshot.id] as const
  const terms = index.snapshot.terms.map((term, termIndex) =>
    printIndexTerm(schema, table, term, [...path, "terms", termIndex], diagnostics),
  )

  if (terms.some((term) => term === undefined)) {
    return undefined
  }

  const options = [
    `physicalName: ${literal(index.snapshot.physicalName)}`,
    `unique: ${index.snapshot.unique ? "true" : "false"}`,
  ]

  if (index.snapshot.predicate !== undefined) {
    const predicate = catalogExpressionData(
      index.snapshot.predicate,
      schema,
      [...path, "predicate"],
      diagnostics,
    )

    if (predicate === undefined) {
      return undefined
    }

    options.push(`where: _catalogPredicate(${predicate})`)
  }

  if (index.snapshot.includedColumns !== undefined) {
    const included = printColumns(
      table,
      index.snapshot.includedColumns,
      [...path, "includedColumns"],
      diagnostics,
    )

    if (included === undefined) {
      return undefined
    }

    options.push(`include: [${included.join(", ")}]`)
  }

  if (index.snapshot.dialect !== undefined) {
    const extension = printExtension(
      index.snapshot.dialect,
      schema,
      [...path, "dialect"],
      diagnostics,
    )

    if (extension === undefined) {
      return undefined
    }

    options.push(`dialect: ${extension}`)
  }

  return `${literal(index.name)}: _qubu.index(
  [${terms.join(", ")}],
  { ${options.join(", ")} }
),`
}

function printIndexTerm(
  schema: ResolvedSchema,
  table: ResolvedTable,
  term: SnapshotIndexTerm,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  if (term.kind !== "order") {
    return printIndexTermExpression(schema, table, term, path, diagnostics)
  }

  const expression = printIndexTermExpression(
    schema,
    table,
    term.expression,
    [...path, "expression"],
    diagnostics,
  )

  if (expression === undefined) {
    return undefined
  }

  return `_qubu.order(${expression}, ${
    term.direction === undefined ? "undefined" : literal(term.direction)
  }, ${term.nulls === undefined ? "undefined" : literal(term.nulls)})`
}

function printIndexTermExpression(
  schema: ResolvedSchema,
  table: ResolvedTable,
  expression: SnapshotIndexTermExpression,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  if (expression.kind === "expression") {
    return printExpression(expression.expression, schema, [...path, "expression"], diagnostics)
  }

  const column = table.columnsBySnapshotId.get(expression.column)

  if (column === undefined) {
    diagnostics.push(
      sourceError(`Index column "${expression.column}" was not resolved`, [...path, "column"]),
    )
    return undefined
  }

  return `_current.columns[${literal(column.name)}]`
}

function printColumns(
  table: ResolvedTable,
  ids: readonly string[],
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
  binding = "_current",
): readonly string[] | undefined {
  const result: string[] = []

  for (const [index, id] of ids.entries()) {
    const column = table.columnsBySnapshotId.get(id)

    if (column === undefined) {
      diagnostics.push(sourceError(`Column "${id}" was not resolved`, [...path, "columns", index]))
      continue
    }

    result.push(`${binding}.columns[${literal(column.name)}]`)
  }

  return result.length === ids.length && result.length > 0 ? result : undefined
}

function printExpression(
  expression: SnapshotExpression,
  schema: ResolvedSchema,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  const data = catalogExpressionData(expression, schema, path, diagnostics)

  return data === undefined ? undefined : `_qubu.unsafeSchemaSql(${data})`
}

function catalogExpressionData(
  expression: SnapshotExpression,
  schema: ResolvedSchema,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  if (
    expression.expressionKind !== "unsafe" ||
    expression.dialect !== schema.dialect ||
    expression.sql.trim().length === 0
  ) {
    diagnostics.push(
      sourceError(
        "Catalog expressions must be non-empty, unsafe, and tagged for the selected dialect",
        path,
      ),
    )
    return undefined
  }

  return `{ dialect: ${literal(expression.dialect)}, sql: ${literal(expression.sql)} }`
}

function printExtension(
  extension: SnapshotDialectExtension,
  schema: ResolvedSchema,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  if (
    extension.dialect !== schema.dialect ||
    extension.version !== 1 ||
    !isJsonObject(extension.data) ||
    Object.hasOwn(extension.data, "dialect")
  ) {
    diagnostics.push(
      sourceError(
        'Dialect extensions must be v1 object data for the selected dialect and cannot contain a data field named "dialect"',
        path,
      ),
    )
    return undefined
  }

  const data = extension.data
  const entries = Object.keys(data)
    .sort()
    .map((key) => `[${literal(key)}]: ${printJsonValue(data[key])}`)

  return `{ dialect: ${literal(extension.dialect)}${
    entries.length === 0 ? "" : `, ${entries.join(", ")}`
  } }`
}

function printSnapshotLiteral(
  value: SnapshotLiteral,
  path: readonly (string | number)[],
  diagnostics: CodegenDiagnostic[],
): string | undefined {
  switch (value.kind) {
    case "null": {
      return "null"
    }

    case "boolean": {
      return value.value ? "true" : "false"
    }

    case "string": {
      return literal(value.value)
    }

    case "bigint": {
      return `BigInt(${literal(value.value)})`
    }

    case "number": {
      const number = Number(value.value)

      if (!Number.isFinite(number)) {
        diagnostics.push(
          sourceError("Default number literals must be finite", [...path, "default"]),
        )
        return undefined
      }

      return Object.is(number, -0) ? "0" : String(number)
    }
  }
}

function printJsonValue(value: SnapshotJsonValue): string {
  if (value === null) {
    return "null"
  }

  if (typeof value === "string") {
    return literal(value)
  }

  if (typeof value === "boolean") {
    return value ? "true" : "false"
  }

  if (typeof value === "number") {
    return Object.is(value, -0) ? "0" : String(value)
  }

  if (Array.isArray(value)) {
    return `[${value.map(printJsonValue).join(", ")}]`
  }

  return `{ ${Object.keys(value)
    .sort()
    .map(
      (key) =>
        `[${literal(key)}]: ${printJsonValue(
          (value as Readonly<Record<string, SnapshotJsonValue>>)[key],
        )}`,
    )
    .join(", ")} }`
}

function applicationType(value: CodegenApplicationType): string {
  return value
}

function sqlDomainType(value: CodegenSqlDomain): string {
  switch (value) {
    case "unknown": {
      return "_qubu.SqlUnknown"
    }

    case "integer": {
      return "_qubu.SqlInteger"
    }

    case "decimal": {
      return "_qubu.SqlDecimal"
    }

    case "text": {
      return "_qubu.SqlText"
    }

    case "boolean": {
      return "_qubu.SqlBoolean"
    }

    case "date": {
      return "_qubu.SqlDate"
    }

    case "timestamp": {
      return "_qubu.SqlTimestamp"
    }

    case "uuid": {
      return "_qubu.SqlUuid"
    }

    case "json": {
      return "_qubu.SqlJson"
    }

    case "bigint": {
      return "_qubu.SqlBigInt"
    }

    case "binary": {
      return "_qubu.SqlBinary"
    }
  }
}

function sourceError(message: string, path: readonly (string | number)[]): CodegenDiagnostic {
  return {
    severity: "error",
    code: "unrepresentable-fact",
    message,
    path,
  }
}

function literal(value: string): string {
  return JSON.stringify(value).replaceAll("\u2028", "\\u2028").replaceAll("\u2029", "\\u2029")
}

function capitalize(value: string): string {
  return `${value.slice(0, 1).toUpperCase()}${value.slice(1)}`
}

function indent(value: string, spaces: number): string {
  const prefix = " ".repeat(spaces)

  return value
    .split("\n")
    .map((line) => `${prefix}${line}`)
    .join("\n")
}

function isJsonObject(
  value: SnapshotJsonValue,
): value is Readonly<Record<string, SnapshotJsonValue>> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}
